--Criação do Banco de Dados--
CREATE TABLE Contas(
Id INT IDENTITY (1,1) PRIMARY KEY, --CRIAÇAÕ DAS TABELAS EM AUTOMATICO--
Titular NVARCHAR(30) NOT NULL,--30 CARACTERES--
Numero_da_conta INT NOT NULL UNIQUE,
Saldo DECIMAL(10,2) NOT NULL, 
);
GO